---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  plugin_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "stack --version"
        env:
          GITHUB_API_TOKEN: ${{ github.token }}

  python_test:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: actions/checkout@v2
      - run: python3 --version
      - run: python3 -m unittest

