---
name: build

on: [push]

jobs:
  python-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m unittest

  asdf-tests:
    runs-on: ubuntu-latest
    steps:
      - uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "stack --version"
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
