---
name: build

on:
  push:
    branches: [master]
  pull_request:
    branches: [master]

jobs:
  python-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: '3.x'
      - run: python -m unittest

  asdf-tests:
    strategy:
      matrix:
        os: [macos-latest, ubuntu-latest]

    runs-on: ${{ matrix.os }}

    steps:
      - uses: asdf-vm/actions/plugin-test@v1
        with:
          command: "stack --version"
        env:
          GITHUB_API_TOKEN: ${{ github.token }}
