---
name: CI

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v1
        with:
          node-version: '12.x'
      - run: npm install
      - run: npm test
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - uses: asdf-vm/actions/plugin-test@v1.0.0
        with:
          command: "stack --version"
        env:
          GITHUB_API_TOKEN: ${{ secrets.GITHUB_TOKEN }}
